name: submission_bmafp
description: Submission for Dicoding course Belajar Membuat Aplikasi Flutter untuk Pemula.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  
  assets:
    - images/
    - images/movies/adam_project/
    - images/movies/amazing_spiderman/
    - images/movies/avatar/
    - images/movies/avengers_endgame/
    - images/movies/avengers_infinity_war/
    - images/movies/bad_guys/
    - images/movies/black_widow/
    - images/movies/blacklight/
    - images/movies/encanto/
    - images/movies/godzilla_vs_kong/
    - images/movies/joker/
    - images/movies/mortal_kombat/
    - images/movies/raya_last_dragon/
    - images/movies/ron_gone_wrong/
    - images/movies/scream/
    - images/movies/sing2/
    - images/movies/snyders_justice_league/
    - images/movies/sonic_hedgehog2/
    - images/movies/spiderman_nwh/
    - images/movies/the_batman/
    - images/movies/the_dark_knight/
    - images/movies/tom_jerry/
    - images/movies/turning_red/
    - images/tv/american_horror/
    - images/tv/euphoria/
    - images/tv/got/
    - images/tv/grimm/
    - images/tv/halo/
    - images/tv/house/
    - images/tv/legacies/
    - images/tv/lucifer/
    - images/tv/midnight_mass/
    - images/tv/people_puzzler/
    - images/tv/reacher/
    - images/tv/ricknmorty/
    - images/tv/riverdale/
    - images/tv/stranger_things/
    - images/tv/swat/
    - images/tv/the_flash/
    - images/tv/the_simpsons/
    - images/tv/tonight_show/
    - images/tv/vikings/
    - images/tv/walking_dead/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
    - family: Comic Neue
      fonts:
        - asset: fonts/ComicNeue-Regular.ttf
