import '../commons/constant.dart';
import '../commons/styles.dart';
import 'Author.dart';
import 'Film.dart';
import 'Role.dart';

class Movies implements Film {
  @override
  final String type = 'movies';

  @override
  final String title,
    overview,
    dateRelease,
    duration,
    posterAsset,
    backdropAsset;

  @override
  final String? certificate;

  @override
  final int userScore;

  @override
  final Map<Author, Role>? authors;

  @override
  final List<String>? genres, keywords, postersNetwork;

  Movies({
    required this.title,
    required this.overview,
    required this.dateRelease,
    required this.certificate,
    required this.duration,
    required this.posterAsset,
    required this.backdropAsset,
    required this.userScore,
    required this.authors,
    required this.genres,
    required this.keywords,
    required this.postersNetwork,
  });
}

var moviesList = <Movies>[
  Movies(
    title: 'Turning Red',
    overview: 'Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.',
    dateRelease: 'Mar 01, 2022',
    certificate: Constant.pg,
    duration: '1h 40m',
    posterAsset: Constant.moviesImagePath('turning_red', Constant.poster),
    backdropAsset: Constant.moviesImagePath('turning_red', Constant.backdrop),
    userScore: Integer.score75,
    authors: {
      Author(authorName: 'Domee Shi'): Role(roleNames: ['Director', 'Screenplay', 'Story']),
      Author(authorName: 'Julia Cho'): Role(roleNames: ['Screenplay', 'Story']),
      Author(authorName: 'Sarah Streicher'): Role(roleNames: ['Story']),
    },
    genres: [ Constant.animation, Constant.family, Constant.comedy, Constant.fantasy ],
    keywords: [ 'canada', 'panda', 'friendship', 'animal', 'ancestor', '2000s', 'teens', 'perfectionist', 'protagonist', 'toronto', 'red panda' ],
    postersNetwork: [
      'https://www.themoviedb.org/t/p/w220_and_h330_face/g2NL3MI9z2f06T25sThz4FLeQKR.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/efhdIab688vcIm6r0JPKy4H2Ytf.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/3hLfmWPaVpJJDjIy115I97rvleo.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/otHc7rnEZpcNMSRuNpTvMgLyuTB.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/yhnd0WtRxm0SEXTJ9k69vdrTMzs.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/kc0YEjL5iLjEbedhpqqpaaUEPZa.jpg',
    ],
  ),
  Movies(
    title: 'Spider-Man: No Way Home',
    overview: 'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.',
    dateRelease: 'Dec 15, 2021',
    certificate: Constant.pg13,
    duration: '2h 28m',
    posterAsset: Constant.moviesImagePath('spiderman_nwh', Constant.poster),
    backdropAsset: Constant.moviesImagePath('spiderman_nwh', Constant.backdrop),
    userScore: Integer.score85 - Integer.shortRuntime,
    authors: {
      Author(authorName: 'Steve Ditko'): Role(roleNames: ['Characters']),
      Author(authorName: 'Stan Lee'): Role(roleNames: ['Characters']),
      Author(authorName: 'Jon Watts'): Role(roleNames: ['Director']),
      Author(authorName: 'Erik Sommers'): Role(roleNames: ['Writer']),
      Author(authorName: 'Chris McKenna'): Role(roleNames: ['Writer']),
    },
    genres: [ Constant.action, Constant.adventure, Constant.scifi ],
    keywords: [ 'hero', 'villain', 'magic', 'superhero', 'masked vigilante', 'nostalgic', 'marvel', 'multiverse', 'teenager', 'sequel', 'fan service' ],
    postersNetwork: [
      'https://www.themoviedb.org/t/p/w220_and_h330_face/hyN61TWnsRqGY9vunR9wpLBzPpa.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/j5f5bRlpChRuyHdexmeSnQmklDt.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/tomAFJjfSCpsufKh1oYcoLmNjT9.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/5pVJ9SuuO72IgN6i9kMwQwnhGHG.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/hQDShpLeeSNAqKCdtv0LBEEoy5t.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/qklitHnYo0XO9QLW4RP51GP4CC1.jpg',
    ],
  ),
  Movies(
    title: 'The Adam Project',
    overview: 'After accidentally crash-landing in 2022, time-traveling fighter pilot Adam Reed teams up with his 12-year-old self on a mission to save the future.',
    dateRelease: 'Mar 11, 2022',
    certificate: Constant.pg13,
    duration: '1h 46m',
    posterAsset: Constant.moviesImagePath('adam_project', Constant.poster),
    backdropAsset: Constant.moviesImagePath('adam_project', Constant.backdrop),
    userScore: Integer.score75 - Integer.nybble,
    authors: {
      Author(authorName: 'Shawn Levy'): Role(roleNames: ['Director']),
      Author(authorName: 'Jennifer Flackett'): Role(roleNames: ['Screenplay']),
      Author(authorName: 'T. S. Nowlin'): Role(roleNames: ['Screenplay']),
      Author(authorName: 'Mark Levin'): Role(roleNames: ['Screenplay']),
      Author(authorName: 'Jonathan Tropper'): Role(roleNames: ['Writer']),
    },
    genres: [ Constant.action, Constant.adventure, Constant.comedy, Constant.scifi, Constant.drama ],
    keywords: [ 'time travel', 'escape', 'explore' ],
    postersNetwork: [
      'https://www.themoviedb.org/t/p/w220_and_h330_face/sI3hQMTyrF9F8jU1qA8qPHLKCgG.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/uEwGbO7fKqdt6PSoIOR5khAudmF.jpg',
    ],
  ),
  Movies(
    title: 'Encanto',
    overview: 'The tale of an extraordinary family, the Madrigals, who live hidden in the mountains of Colombia, in a magical house, in a vibrant town, in a wondrous, charmed place called an Encanto. The magic of the Encanto has blessed every child in the family with a unique gift from super strength to the power to heal—every child except one, Mirabel. But when she discovers that the magic surrounding the Encanto is in danger, Mirabel decides that she, the only ordinary Madrigal, might just be her exceptional family\'s last hope.',
    dateRelease: 'Nov 24, 2021',
    certificate: Constant.pg,
    duration: '1h 42m',
    posterAsset: Constant.moviesImagePath('encanto', Constant.poster),
    backdropAsset: Constant.moviesImagePath('encanto', Constant.backdrop),
    userScore: Integer.score75 + Integer.bitRadix,
    authors: {
      Author(authorName: 'Jared Bush'): Role(roleNames: ['Director', 'Screenplay']),
      Author(authorName: 'Byron Howard'): Role(roleNames: ['Director']),
      Author(authorName: 'Charise Castro Smith'): Role(roleNames: ['Screenplay']),
    },
    genres: [ Constant.animation, Constant.comedy, Constant.family, Constant.fantasy ],
    keywords: [ 'magic', 'musical', 'forest', 'family relationships', 'female protagonist', 'colombia' ],
    postersNetwork: [
      'https://www.themoviedb.org/t/p/w220_and_h330_face/feKU4spZTEVz6UC63EBVdGAcBN7.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/7M8bMABEbhGkC6z36WEsDttDk6F.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/hCMD9Sn1cV6FShnvrJJEgUNP3ib.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/fnsEJAH8RY8g76cZefzZ0yOgjp0.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/7wkvW7aWG4DRnppXAFNcS44nd8r.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/wMil69k9N0tncavxToM9NAa2UjS.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/bu9yAVzA8boMVDKlZKgZf2b1XIk.jpg',
    ],
  ),
  Movies(
    title: 'Blacklight',
    overview: 'Travis Block is a shadowy Government agent who specializes in removing operatives whose covers have been exposed. He then has to uncover a deadly conspiracy within his own ranks that reaches the highest echelons of power.',
    dateRelease: 'Feb 10, 2022',
    certificate: Constant.pg13,
    duration: '1h 44m',
    posterAsset: Constant.moviesImagePath('blacklight', Constant.poster),
    backdropAsset: Constant.moviesImagePath('blacklight', Constant.backdrop),
    userScore: Integer.score55 + Integer.nybble,
    authors: {
      Author(authorName: 'Mark Williams'): Role(roleNames: ['Director', 'Writer']),
      Author(authorName: 'Nick May'): Role(roleNames: ['Screenplay', 'Story']),
      Author(authorName: 'Brandon Reavis'): Role(roleNames: ['Story']),
    },
    genres: [ Constant.action, Constant.thriller ],
    keywords: null,
    postersNetwork: [
      'https://www.themoviedb.org/t/p/w220_and_h330_face/1KHoDh6NW8SWOJu8JnFe6wWaMD3.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/2u0jXOzAUtjX6un1xu5i7R4RvEq.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/uJxFeFIlyQdN4XSCTqBTxLXHbN4.jpg',
    ],
  ),
  Movies(
    title: 'The Batman',
    overview: 'In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.',
    dateRelease: 'Mar 01, 2022',
    certificate: Constant.pg13,
    duration: '2h 56m',
    posterAsset: Constant.moviesImagePath('the_batman', Constant.poster),
    backdropAsset: Constant.moviesImagePath('the_batman', Constant.backdrop),
    userScore: Integer.score75 + Integer.nybble,
    authors: {
      Author(authorName: 'Matt Reeves'): Role(roleNames: ['Director', 'Writer']),
      Author(authorName: 'Bill Finger'): Role(roleNames: ['Characters']),
      Author(authorName: 'Bob Kane'): Role(roleNames: ['Characters']),
      Author(authorName: 'Peter Craig'): Role(roleNames: ['Writer']),
    },
    genres: [ Constant.crime, Constant.mystery, Constant.thriller ],
    keywords: [ 'millionaire', 'social injustice', 'masked superhero', 'neo-noir', 'vengeance', 'political corruption', 'nightclub', 'police', 'politician', 'crime fighter', 'secret identity', 'investigation' ],
    postersNetwork: [
      'https://www.themoviedb.org/t/p/w220_and_h330_face/3VFI3zbuNhXzx7dIbYdmvBLekyB.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/lERJ6FxBxggf8OWkuA8N656NFMN.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/pev79DpUojF5qaWwedoEa2LT31i.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/26GuBJpd9vLoCdrG5ocadINtt0h.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/3WGuOIXrw8QHSUF2RyIa1kHAWfk.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/kq34KdAGvFzwfiGv6BSdmUvI8KY.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/5qZXyAF1Q0KZbIYP9wxl0jXzXnw.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/e1pa0T32ZedIqUZ28YbXltqq3qc.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/1RO3i4kSLWyBAn9M8ul4FVC5lfY.jpg',
    ],
  ),
  Movies(
    title: 'Sonic The Hedgehog 2',
    overview: 'After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.',
    dateRelease: 'Mar 30, 2022',
    certificate: Constant.pg,
    duration: '2h 2m',
    posterAsset: Constant.moviesImagePath('sonic_hedgehog2', Constant.poster),
    backdropAsset: Constant.moviesImagePath('sonic_hedgehog2', Constant.backdrop),
    userScore: Integer.score75 + Integer.nybble,
    authors: {
      Author(authorName: 'Josh Miller'): Role(roleNames: ['Screenplay', 'Story']),
      Author(authorName: 'Patrick Casey'): Role(roleNames: ['Screenplay', 'Story']),
      Author(authorName: 'Jeff Fowler'): Role(roleNames: ['Director']),
      Author(authorName: 'John Whittington'): Role(roleNames: ['Screenplay']),
    },
    genres: [ Constant.action, Constant.scifi, Constant.comedy, Constant.family ],
    keywords: [ 'sequel', 'based on', 'video game', 'hedgehog', 'live action', 'animation' ],
    postersNetwork: [
      'https://www.themoviedb.org/t/p/w220_and_h330_face/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/6zNROEm1IFpUy1SbCbxoQYFn46v.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/kmM5SO77YMttewSnzuRhv5KLYWr.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/2S4NZshqoCEf8yHxjuqQ2HNoMaH.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/inoEi49KGdEHhJMKXDQA5Vqxwwe.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/6JiQPiDNHE1MToKkbr1WblYsQBd.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/33yGzndgYOu8xz72UkzN65Olhva.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/5z20L2jfd9YDWvwwEdRwBqODvn9.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/4uecpnbhjtWl9T2bYRb8JTs2IzI.jpg',
    ],
  ),
  Movies(
    title: 'Sing 2',
    overview: 'Buster and his new cast now have their sights set on debuting a new show at the Crystal Tower Theater in glamorous Redshore City. But with no connections, he and his singers must sneak into the Crystal Entertainment offices, run by the ruthless wolf mogul Jimmy Crystal, where the gang pitches the ridiculous idea of casting the lion rock legend Clay Calloway in their show. Buster must embark on a quest to find the now-isolated Clay and persuade him to return to the stage.',
    dateRelease: 'Dec 01, 2021',
    certificate: Constant.pg,
    duration: '1h 50m',
    posterAsset: Constant.moviesImagePath('sing2', Constant.poster),
    backdropAsset: Constant.moviesImagePath('sing2', Constant.backdrop),
    userScore: Integer.score85 - Integer.nybble,
    authors: {
      Author(authorName: 'Garth Jennings'): Role(roleNames: ['Characters', 'Director', 'Writer']),
    },
    genres: [ Constant.animation, Constant.comedy, Constant.family, Constant.music ],
    keywords: [ 'stage', 'singing', 'animal', 'anthropomorphism' ],
    postersNetwork: [
      'https://www.themoviedb.org/t/p/w220_and_h330_face/sgNDmH3ucT1hi60ECLsasMloKEF.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/422ZRu3zTdPnR4e2C0SRMM69CTq.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/mC0zoSvnmGw4nFBGVfkeFp7lcAU.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/zCIqUFNQ7yl2hCevVANXJmvlbzs.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/akChZ65mRR0vk6ckeB02o5NT2YV.jpg',
    ],
  ),
  Movies(
    title: 'Scream',
    overview: 'Twenty-five years after a streak of brutal murders shocked the quiet town of Woodsboro, a new killer has donned the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town’s deadly past.',
    dateRelease: 'Jan 12, 2022',
    certificate: Constant.r,
    duration: '1h 54m',
    posterAsset: Constant.moviesImagePath('scream', Constant.poster),
    backdropAsset: Constant.moviesImagePath('scream', Constant.backdrop),
    userScore: Integer.score65 + Integer.shortRuntime,
    authors: {
      Author(authorName: 'Kevin Williamson'): Role(roleNames: ['Characters']),
      Author(authorName: 'Tyler Gillett'): Role(roleNames: ['Director']),
      Author(authorName: 'Matt Bettinelli-Olpin'): Role(roleNames: ['Director']),
      Author(authorName: 'James Vanderbilt'): Role(roleNames: ['Screenplay']),
      Author(authorName: 'Guy Busick'): Role(roleNames: ['Screenplay']),
    },
    genres: [ Constant.horror, Constant.mystery, Constant.thriller ],
    keywords: [ 'mask', 'murder', 'reboot', 'copycat killer', 'slasher', 'hallucination', 'killing spree', 'fandom', 'metacinema', 'crime', 'killer', 'mystery' ],
    postersNetwork: [
      'https://www.themoviedb.org/t/p/w220_and_h330_face/mOWp8teSWa3acjlffsEvvOkFleF.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/qvASAp0ZKkza023gjK1Tf2iiEos.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/aF0ELNWvUNa5PuZcXMlkPKxKqWe.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/bxWLEggd2mLmYPXKREQCmLkMfUs.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/kIVRXCKu6D3Lb7MoEcA2RSnsxqW.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/ixfWCjKIfF4RnppcVIDPxjBRbbD.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/bsu87k2QXmcxQOrjptyGxzamXCZ.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/f3AEn78F0ey2F2J2Vt0nqbQcIUq.jpg',
    ],
  ),
  Movies(
    title: 'Avatar',
    overview: 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
    dateRelease: 'Dec 10, 2009',
    certificate: Constant.pg13,
    duration: '2h 42m',
    posterAsset: Constant.moviesImagePath('avatar', Constant.poster),
    backdropAsset: Constant.moviesImagePath('avatar', Constant.backdrop),
    userScore: Integer.score75,
    authors: {
      Author(authorName: 'James Cameron'): Role(roleNames: ['Director', 'Writer']),
    },
    genres: [ Constant.action, Constant.adventure, Constant.fantasy, Constant.scifi ],
    keywords: [ 'future', 'alien', 'tribe', 'marine', 'soldier', 'space opera', 'planet', 'battle', 'anti war', 'mind and soul', 'power relations', 'space', 'society', 'culture clash', 'love affair' ],
    postersNetwork: [
      'https://www.themoviedb.org/t/p/w220_and_h330_face/6EiRUJpuoeQPghrs3YNktfnqOVh.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/7paC3UJ0P2P3DeykgQhUD1hnQJO.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/5XihRwu80XcTfh0O1uzkraFc7U4.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/yhXvZnaWLXDClVp7AsLRqSEznAx.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/erNwtAitkJJ6wKxFt3EMJsEb2VO.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/ricxDDHSAdRYA4lpqdHoInputIw.jpg',
    ],
  ),
  Movies(
    title: 'The Bad Guys',
    overview: 'When the infamous Bad Guys are finally caught after years of countless heists and being the world’s most-wanted villains, Mr. Wolf brokers a deal to save them all from prison.',
    dateRelease: 'Mar 17, 2022',
    certificate: Constant.pg,
    duration: '1h 40m',
    posterAsset: Constant.moviesImagePath('bad_guys', Constant.poster),
    backdropAsset: Constant.moviesImagePath('bad_guys', Constant.backdrop),
    userScore: Integer.score75 + Integer.high,
    authors: {
      Author(authorName: 'Pierre Perifel'): Role(roleNames: ['Director']),
      Author(authorName: 'Hilary Winston'): Role(roleNames: ['Writer']),
      Author(authorName: 'Etan Cohen'): Role(roleNames: ['Writer']),
    },
    genres: [ Constant.animation, Constant.comedy, Constant.action, Constant.family, Constant.crime ],
    keywords: [ 'based on graphic novel' ],
    postersNetwork: [
      'https://www.themoviedb.org/t/p/w220_and_h330_face/qT2LvVFPB8Y7O0ER5LcBcNDm07E.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/34voJ60RYBYuM3Vh6Q1fZXZ9OTd.jpg',
    ],
  ),
  Movies(
    title: 'Tom and Jerry: Cowboy Up!',
    overview: 'This time, the rivals team up to help a cowgirl and her brother save their homestead from a greedy land-grabber, and they’re going to need some help! Jerry’s three precocious nephews are all ready for action, and Tom is rounding up a posse of prairie dogs. But can a ragtag band of varmints defeat a deceitful desperado determined to deceive a damsel in distress? No matter what happens with Tom and Jerry in the saddle, it’ll be a rootin’ tootin’ good time!',
    dateRelease: 'Jan 24, 2022',
    certificate: Constant.nr,
    duration: '1h 15m',
    posterAsset: Constant.moviesImagePath('tom_jerry', Constant.poster),
    backdropAsset: Constant.moviesImagePath('tom_jerry', Constant.backdrop),
    userScore: Integer.score75 - Integer.int5,
    authors: {
      Author(authorName: 'William Hanna'): Role(roleNames: ['Characters']),
      Author(authorName: 'Joseph Barbera'): Role(roleNames: ['Characters']),
      Author(authorName: 'Darrell Van Citters'): Role(roleNames: ['Director']),
      Author(authorName: 'Will Finn'): Role(roleNames: ['Story']),
      Author(authorName: 'William Waldner'): Role(roleNames: ['Teleplay']),
    },
    genres: [ Constant.animation, Constant.comedy, Constant.family, Constant.western ],
    keywords: null,
    postersNetwork: [
      'https://www.themoviedb.org/t/p/w220_and_h330_face/fEXd73ZkvSa4DYBzWpIDwz0Ri4r.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/q0mdCfXNkQHu961k94Fe2dNtvMm.jpg',
    ],
  ),
  Movies(
    title: 'Ron\'s Gone Wrong',
    overview: 'In a world where walking, talking, digitally connected bots have become children\'s best friends, an 11-year-old finds that his robot buddy does not quite work the same as the others do.',
    dateRelease: 'Oct 15, 2021',
    certificate: Constant.pg,
    duration: '1h 47m',
    posterAsset: Constant.moviesImagePath('ron_gone_wrong', Constant.poster),
    backdropAsset: Constant.moviesImagePath('ron_gone_wrong', Constant.backdrop),
    userScore: Integer.score85 - Integer.nybble,
    authors: {
      Author(authorName: 'Sarah Smith'): Role(roleNames: ['Director', 'Screenplay']),
      Author(authorName: 'Jean-Philippe Vine'): Role(roleNames: ['Director']),
      Author(authorName: 'Peter Baynham'): Role(roleNames: ['Writer']),
    },
    genres: [ Constant.animation, Constant.scifi, Constant.family, Constant.comedy ],
    keywords: [ 'family', 'best friend forever', 'bff' ],
    postersNetwork: [
      'https://www.themoviedb.org/t/p/w220_and_h330_face/plzgQAXIEHm4Y92ktxU6fedUc0x.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/gA9QxSravC2EVEkEKgyEmDrfL0e.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/2gq9sEE2iDRqKx8OiZP6mYSTq4.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/yMupQ2lgqfWQlkunjbAHjboxNgB.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/mbYiTBKRjg64qLwcsqYFxHJNYVI.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/7RgLosVVs7Vfor45yul1H4f8A3.jpg',
    ],
  ),
  Movies(
    title: 'Mortal Kombat',
    overview: 'Washed-up MMA fighter Cole Young, unaware of his heritage, and hunted by Emperor Shang Tsung\'s best warrior, Sub-Zero, seeks out and trains with Earth\'s greatest champions as he prepares to stand against the enemies of Outworld in a high stakes battle for the universe.',
    dateRelease: 'Apr 07, 2021',
    certificate: Constant.r,
    duration: '1h 50m',
    posterAsset: Constant.moviesImagePath('mortal_kombat', Constant.poster),
    backdropAsset: Constant.moviesImagePath('mortal_kombat', Constant.backdrop),
    userScore: Integer.score75 - Integer.shortRuntime,
    authors: {
      Author(authorName: 'Greg Russo'): Role(roleNames: ['Screenplay', 'Story']),
      Author(authorName: 'Simon McQuoid'): Role(roleNames: ['Director']),
      Author(authorName: 'Dave Callaham'): Role(roleNames: ['Screenplay']),
      Author(authorName: 'Oren Uziel'): Role(roleNames: ['Story']),
    },
    genres: [ Constant.action, Constant.fantasy, Constant.adventure ],
    keywords: [ 'magic', 'gods', 'fighting', 'alternate dimension', 'ninja fighter', 'shaolin monk', 'based on video game', 'martial arts tournament', 'hand to hand combat' ],
    postersNetwork: [
      'https://www.themoviedb.org/t/p/w220_and_h330_face/6Wdl9N6dL0Hi0T1qJLWSz6gMLbd.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/ybrX94xQm8lXYpZAPRmwD9iIbWP.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/irSLEqJfb2AVEKSuW39OgZSbr6M.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/yuF8DhVQmeyeEq3qxGyiD7uD9Zn.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/AdH4kZD0TO6mG2RowV7rbEOKviC.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/pUGgdCmlLbMwAyswafBFjFosFpI.jpg',
    ],
  ),
  Movies(
    title: 'Zack Snyder\'s Justice League',
    overview: 'Determined to ensure Superman\'s ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.',
    dateRelease: 'Mar 18, 2021',
    certificate: Constant.r,
    duration: '4h 2m',
    posterAsset: Constant.moviesImagePath('snyders_justice_league', Constant.poster),
    backdropAsset: Constant.moviesImagePath('snyders_justice_league', Constant.backdrop),
    userScore: Integer.score85 - Integer.bitRadix,
    authors: {
      Author(authorName: 'Zack Snyder'): Role(roleNames: ['Director', 'Story']),
      Author(authorName: 'Chris Terrio'): Role(roleNames: ['Screenplay', 'Story']),
      Author(authorName: 'Bob Kane'): Role(roleNames: ['Characters']),
      Author(authorName: 'Jack Kirby'): Role(roleNames: ['Characters']),
      Author(authorName: 'Jerry Siegel'): Role(roleNames: ['Characters']),
      Author(authorName: 'Joe Shuster'): Role(roleNames: ['Characters']),
      Author(authorName: 'Gardner Fox'): Role(roleNames: ['Characters']),
      Author(authorName: 'Bill Finger'): Role(roleNames: ['Characters']),
      Author(authorName: 'William Moulton Marston'): Role(roleNames: ['Characters']),
      Author(authorName: 'Will Beall'): Role(roleNames: ['Story']),
    },
    genres: [ Constant.action, Constant.adventure, Constant.fantasy, Constant.scifi ],
    keywords: [ 'superhero', 'based on comic', 'superhero team', 'dc extended universe', 'superhero teamup' ],
    postersNetwork: [
      'https://www.themoviedb.org/t/p/w220_and_h330_face/yWmbO5tQNlIpIEt6nNKD72TpXtM.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/wFl2rumfzQJzTf50WqmK7zDg6Aa.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/dpt8G3BZa4ZUEu67JOh4mCLK40p.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/eZEYRjsi659CWj4GZ9edDRnHN9g.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/pgb96Oxdc6uEjhu1o3e71pKXAPi.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/9x1Kaa4ETCAZUrEaCPXHVqwPuT5.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/p3kyJWjr7SzjeGHr85oIkLidYvE.jpg',
    ],
  ),
  Movies(
    title: 'Joker',
    overview: 'During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.',
    dateRelease: 'Oct 02, 2019',
    certificate: Constant.r,
    duration: '2h 2m',
    posterAsset: Constant.moviesImagePath('joker', Constant.poster),
    backdropAsset: Constant.moviesImagePath('joker', Constant.backdrop),
    userScore: Integer.score85 - Integer.shortRuntime,
    authors: {
      Author(authorName: 'Todd Phillips'): Role(roleNames: ['Director', 'Writer']),
      Author(authorName: 'Bob Kane'): Role(roleNames: ['Characters']),
      Author(authorName: 'Jerry Robinson'): Role(roleNames: ['Characters']),
      Author(authorName: 'Bill Finger'): Role(roleNames: ['Characters']),
      Author(authorName: 'Scott Silver'): Role(roleNames: ['Writer']),
    },
    genres: [ Constant.crime, Constant.thriller, Constant.drama ],
    keywords: [ 'villain', 'society', 'street gang', 'clown', 'joker', 'murder', 'criminal mastermind', 'psychological thriller', 'anarchy', '1980s', 'gotham city', 'mental illness', 'dream', 'subway train' ],
    postersNetwork: [
      'https://www.themoviedb.org/t/p/w220_and_h330_face/mZuAPY4ETMQPHhCXIcJ90kd6RaS.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/bfHlGMDq2RqRT1xmjq9NJSzfhCv.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/tfzagTRS9eLEwC3UMmYqiA48D8k.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/8DEP71rRCE8F07wTDFT649foXTy.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/2H6O9wJohvBlrelCOer4RKPW72L.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/nC8ywMJWAOVRLN9rfUQ2zDaTNa9.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/jIIHHkQbX3JYh2A9ghXeyuC0FBP.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/oTPZNkh61Qfh91h4FJvZ7aVsKWb.jpg',
    ],
  ),
  Movies(
    title: 'Black Widow',
    overview: 'Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.',
    dateRelease: 'Jul 07, 2021',
    certificate: Constant.pg13,
    duration: '2h 14m',
    posterAsset: Constant.moviesImagePath('black_widow', Constant.poster),
    backdropAsset: Constant.moviesImagePath('black_widow', Constant.backdrop),
    userScore: Integer.score75,
    authors: {
      Author(authorName: 'Cate Shortland'): Role(roleNames: ['Director']),
      Author(authorName: 'Eric Pearson'): Role(roleNames: ['Screenplay']),
      Author(authorName: 'Jac Schaeffer'): Role(roleNames: ['Story']),
      Author(authorName: 'Ned Benson'): Role(roleNames: ['Story']),
    },
    genres: [ Constant.action, Constant.adventure, Constant.scifi ],
    keywords: [ 'spy', 'assassin', 'hero', 'kgb', 'based on comic', 'female assassin', 'female spy', 'female hero', 'marvel cinematic universe', 'mcu' ],
    postersNetwork: [
      'https://www.themoviedb.org/t/p/w220_and_h330_face/ytnhzdwtj0YfC5NVWrrPRGSGZb7.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/AuUMk8CVzwXD7gef8O5ORNMmkhl.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/p3AABIGWQxbzXSdPSbST4gwDQ03.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/rFBHD0499vOYqH0yHc7R843ErXP.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/LZXNrESIR23nu2DetptWfjAbIS.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/nVuMrCxHMzA9BqwPyeOAY7M6dVi.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/ldXzKSqAoyfBegkp6dI81KDNiNi.jpg',
    ],
  ),
  Movies(
    title: 'Godzilla vs. Kong',
    overview: 'In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.',
    dateRelease: 'Mar 24, 2021',
    certificate: Constant.pg13,
    duration: '1h 53m',
    posterAsset: Constant.moviesImagePath('godzilla_vs_kong', Constant.poster),
    backdropAsset: Constant.moviesImagePath('godzilla_vs_kong', Constant.backdrop),
    userScore: Integer.score75 + Integer.shortRuntime,
    authors: {
      Author(authorName: 'Adam Wingard'): Role(roleNames: ['Director']),
      Author(authorName: 'Eric Pearson'): Role(roleNames: ['Screenplay']),
      Author(authorName: 'Max Borenstein'): Role(roleNames: ['Screenplay']),
      Author(authorName: 'Zach Shields'): Role(roleNames: ['Story']),
      Author(authorName: 'Terry Rossio'): Role(roleNames: ['Story']),
      Author(authorName: 'Michael Dougherty'): Role(roleNames: ['Story']),
    },
    genres: [ Constant.action, Constant.fantasy, Constant.scifi ],
    keywords: [ 'giant monster', 'dinosaur', 'creature feature', 'kaiju', 'sign languages', 'giant ape', 'monsterverse', 'robot dinosaur' ],
    postersNetwork: [
      'https://www.themoviedb.org/t/p/w220_and_h330_face/51tAtnATqN9VizZDnCN0IdCQpXF.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/asmxTLzVSLTkIwybSB0DJHDKw8o.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/ozqOgP05z8QBDUHO8pGhjekhlyP.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/nLDGM891W086lacpK1FuYTuGqW3.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/mO4OYC3SDN8rXzp0J3PyhaUz7tQ.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/5KYaB1CTAklQHm846mHTFkozgDN.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/z7J8tFbsq7x2bkuA25cpPFr0nFv.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/m9lD3hXeBf68qLYnc5brnqlzEzA.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/lUn3gBvYwiOcSFoFA8pd7R3mqP2.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/wrwqhLGMwx9AtwhgFHSnwC8z3xs.jpg',
    ],
  ),
  Movies(
    title: 'The Amazing Spider-Man',
    overview: 'In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.',
    dateRelease: 'Jun 23, 2012',
    certificate: Constant.pg13,
    duration: '2h 16m',
    posterAsset: Constant.moviesImagePath('amazing_spiderman', Constant.poster),
    backdropAsset: Constant.moviesImagePath('amazing_spiderman', Constant.backdrop),
    userScore: Integer.score65 + Integer.bitRadix,
    authors: {
      Author(authorName: 'James Vanderbilt'): Role(roleNames: ['Screenplay', 'Story']),
      Author(authorName: 'Steve Ditko'): Role(roleNames: ['Characters']),
      Author(authorName: 'Stan Lee'): Role(roleNames: ['Characters']),
      Author(authorName: 'Marc Webb'): Role(roleNames: ['Director']),
      Author(authorName: 'Alvin Sargent'): Role(roleNames: ['Screenplay']),
      Author(authorName: 'Steve Kloves'): Role(roleNames: ['Screenplay']),
    },
    genres: [ Constant.action, Constant.adventure, Constant.fantasy ],
    keywords: [ 'vigilante', 'based on comic', 'super power', 'teenage hero', 'virus', 'justice', 'violent death', 'loss on loved one', 'spider bite', 'masked vigilante', 'genetic engineering', 'social outcast' ],
    postersNetwork: [
      'https://www.themoviedb.org/t/p/w220_and_h330_face/bUTvy463oYc7oPflr6eDw3CHWNE.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/sJ80wl69fiWxs3LEwb8yMiHa7F7.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/jIfkQNARYyERqRAq1p1c8xgePp4.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/dQ8TOCYgP9pzQvSb1cmaalYqdb5.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/uiX2jlUHDYjb4kSGGCfhl4yAxIw.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/neWM7JerenLEOU6Gwu8gpWN03rZ.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/rNK9zFuQ68teawUEpSJdfy3bDMO.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/71gOlrJhCVuCGZKDmtad4pUYK2K.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/g8nMoqiTwcQH6WfCKsEzT6TRVkS.jpg',
    ],
  ),
  Movies(
    title: 'Avengers: Infinity War',
    overview: 'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.',
    dateRelease: 'Apr 25, 2018',
    certificate: Constant.pg13,
    duration: '2h 29m',
    posterAsset: Constant.moviesImagePath('avengers_infinity_war', Constant.poster),
    backdropAsset: Constant.moviesImagePath('avengers_infinity_war', Constant.backdrop),
    userScore: Integer.score85 - Integer.bitRadix,
    authors: {
      Author(authorName: 'Joe Russo'): Role(roleNames: ['Director']),
      Author(authorName: 'Anthony Russo'): Role(roleNames: ['Director']),
      Author(authorName: 'Stephen McFeely'): Role(roleNames: ['Screenplay']),
      Author(authorName: 'Christopher Markus'): Role(roleNames: ['Screenplay']),
    },
    genres: [ Constant.adventure, Constant.action, Constant.scifi ],
    keywords: [ 'magic', 'sacrifice', 'space', 'magical object', 'battlefield', 'genocide', 'super power', 'cosmic', 'marvel cinematic universe', 'mcu', 'based on comic', 'superhero' ],
    postersNetwork: [
      'https://www.themoviedb.org/t/p/w220_and_h330_face/ypX47SBSThTbB40AIJ22eOUCpjU.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/bxfCEo5a6t6gxUR9EjJLlqCe73i.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/t8yAfqHvtIQJVq8w98UCY0r58Ic.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/cdkCfpIXOSvNTuhUqikiLqQZOo7.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/rQpd7eMhzQxCF90c8ITNqZDFCQu.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/84EwFHyqNSzijE5UCovtk2aC57v.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/kQPVxIuJUz5AZHFhNDKIRKMOM7P.jpg',
    ],
  ),
  Movies(
    title: 'Avengers: Endgame',
    overview: 'After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos\' actions and restore order to the universe once and for all, no matter what consequences may be in store.',
    dateRelease: 'Apr 24, 2019',
    certificate: Constant.pg13,
    duration: '3h 1m',
    posterAsset: Constant.moviesImagePath('avengers_endgame', Constant.poster),
    backdropAsset: Constant.moviesImagePath('avengers_endgame', Constant.backdrop),
    userScore: Integer.score85 - Integer.bitRadix,
    authors: {
      Author(authorName: 'Joe Russo'): Role(roleNames: ['Director']),
      Author(authorName: 'Anthony Russo'): Role(roleNames: ['Director']),
      Author(authorName: 'Stephen McFeely'): Role(roleNames: ['Screenplay']),
      Author(authorName: 'Christopher Markus'): Role(roleNames: ['Screenplay']),
    },
    genres: [ Constant.adventure, Constant.scifi, Constant.action ],
    keywords: [ 'space travel', 'sequel', 'time travel', 'time machine', 'superhero team', 'marvel cinematic universe', 'mcu', 'alien invasion', 'based on comic', 'final battle', 'alternate timeline', 'relationship' ],
    postersNetwork: [
      'https://www.themoviedb.org/t/p/w220_and_h330_face/5wwfS59CTzc4tlF1GHWy7KUIULc.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/oihnoMVJHcdmUe0FbxWbwk1YbGZ.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/b55H5YuXFPyiCmjDIliFf6EhlUl.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/vFDsVlJghgeIgDJPYahZXKyRVsw.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/yCAzT42NfSuckAZKWg5FvR4pUVc.jpg',
    ],
  ),
  Movies(
    title: 'The Dark Knight',
    overview: 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
    dateRelease: 'Jul 14, 2008',
    certificate: Constant.pg13,
    duration: '2h 32m',
    posterAsset: Constant.moviesImagePath('the_dark_knight', Constant.poster),
    backdropAsset: Constant.moviesImagePath('the_dark_knight', Constant.backdrop),
    userScore: Integer.score85,
    authors: {
      Author(authorName: 'Christopher Nolan'): Role(roleNames: ['Director', 'Screenplay', 'Story']),
      Author(authorName: 'Bob Kane'): Role(roleNames: ['Characters']),
      Author(authorName: 'Jonathan Nolan'): Role(roleNames: ['Screenplay']),
      Author(authorName: 'David S. Goyer'): Role(roleNames: ['Screenplay']),
    },
    genres: [ Constant.drama, Constant.action, Constant.crime, Constant.thriller ],
    keywords: [ 'crime fighter', 'neo-noir', 'based on comic', 'vigilante', 'joker', 'scarecrow', 'sadism', 'secret identity', 'anti hero', 'chaos', 'tragic hero', 'organized crime', 'criminal mastermind', 'super villain', 'district attorney' ],
    postersNetwork: [
      'https://www.themoviedb.org/t/p/w220_and_h330_face/vGYJRor3pCyjbaCpJKC39MpJhIT.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/rqoWYzCuNdQewVfKw6H8dFfg4dd.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/7MQT7G87WK7Y6ZeDB7c6mGRrzK9.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/uruzphNWfIo0MxygPDQ5dvlgEQh.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/bRZRXgW3UTUV1a19qGpGhm6W5uE.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/cFfhGHjxv7sWjXS4uABHJi9mvzW.jpg',
    ],
  ),
  Movies(
    title: 'Raya and the Last Dragon',
    overview: 'Long ago, in the fantasy world of Kumandra, humans and dragons lived together in harmony. But when an evil force threatened the land, the dragons sacrificed themselves to save humanity. Now, 500 years later, that same evil has returned and it’s up to a lone warrior, Raya, to track down the legendary last dragon to restore the fractured land and its divided people.',
    dateRelease: 'Mar 03, 2021',
    certificate: Constant.pg,
    duration: '1h 47m',
    posterAsset: Constant.moviesImagePath('raya_last_dragon', Constant.poster),
    backdropAsset: Constant.moviesImagePath('raya_last_dragon', Constant.backdrop),
    userScore: Integer.score85 - Integer.int5,
    authors: {
      Author(authorName: 'Don Hall'): Role(roleNames: ['Director', 'Story']),
      Author(authorName: 'Carlos López Estrada'): Role(roleNames: ['Director', 'Story']),
      Author(authorName: 'Qui Nguyen'): Role(roleNames: ['Screenplay', 'Story']),
      Author(authorName: 'Adele Lim'): Role(roleNames: ['Screenplay', 'Story']),
      Author(authorName: 'John Ripa'): Role(roleNames: ['Story']),
      Author(authorName: 'Kiel Murray'): Role(roleNames: ['Story']),
      Author(authorName: 'Paul Briggs'): Role(roleNames: ['Story']),
      Author(authorName: 'Dean Wellins'): Role(roleNames: ['Story']),
    },
    genres: [ Constant.family, Constant.fantasy, Constant.animation, Constant.action, Constant.adventure ],
    keywords: [ 'kung fu', 'warrior', 'sword', 'warrior woman', 'dragon', 'vietnamese', 'south asian' ],
    postersNetwork: [
      'https://www.themoviedb.org/t/p/w220_and_h330_face/6t7X3LMwVtCubcmk9HWI1M9RtbK.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/6tdfPVC6kqCVFHqmAGibgYcgw3S.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/bOVBNyWBdBCZIvJLIGeRdpk4MQJ.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/eGn6BLhjm0cD7HegJa6znaI4oX7.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/mLF0w2yTF1RByqIFMRtutoqbqI8.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/6afZmDpJMh2m1mOaVOb1dTO4SJ3.jpg',
      'https://www.themoviedb.org/t/p/w220_and_h330_face/w3Ssoqye87HkTb7xqzF6R8bTS2l.jpg',
    ],
  ),
];